services:
  #watchtower:
   # image: containrrr/watchtower:latest
    #command:
     # -  "--label-enable"
      #-  "--interval"
      #-  "30"
       #- "--rolling-restart"
    #volumes:
     # - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # Add your email here
      - "--certificatesresolvers.myresolver.acme.email=email@email.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    labels:
      - "traefik.enable=true"
      # add your domain here
      - "traefik.http.routers.web.rule=Host(`domain.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
     # - "com.centurylinklabs.watchtower.enable=true"
    build:
      context: .

volumes:
  letsencrypt: